board: kanban
branch: ''
chat_index: 0
chat_links: []
check_lists: []
child_index: 0
column: tasks
column_id: ''
created_at: '2025-11-24 07:40:06.347654'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/api/.codx/tasks/kanban/tasks/.233c79ed-fc45-437a-a4bc-f23e73a3330e.yaml
id: 233c79ed-fc45-437a-a4bc-f23e73a3330e
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: chat
name: ''
parent_id: null
parent_project_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
target_project_id: null
updated_at: '2025-11-24T17:52:42.025322'
url: ''
users: []
visibility: ''
