board: kanban
branch: ''
chat_index: 0
chat_links: []
check_lists: []
child_index: 0
column: tasks
column_id: ''
created_at: '2025-11-24 18:05:11.698615'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/api/.codx/tasks/kanban/tasks/.c635ef0d-c6c5-49d7-8a1b-b2d07ff4234b.yaml
id: c635ef0d-c6c5-49d7-8a1b-b2d07ff4234b
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: chat
name: ''
parent_id: null
parent_project_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
target_project_id: null
updated_at: '2025-11-24T18:06:57.922512'
url: ''
users: []
visibility: ''
