board: kanban
branch: ''
chat_index: 0
chat_links: []
check_lists: []
child_index: 0
column: tasks
column_id: ''
created_at: '2025-11-24 18:10:38.738595'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/api/.codx/tasks/kanban/tasks/.e8ac4895-97cf-44a7-85e4-9db5f4fa0877.yaml
id: e8ac4895-97cf-44a7-85e4-9db5f4fa0877
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: chat
name: ''
parent_id: null
parent_project_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
target_project_id: null
updated_at: '2025-11-24T18:11:49.982063'
url: ''
users: []
visibility: ''
