board: chats
branch: ''
chat_index: 0
chat_links: []
check_lists: []
column: chats
column_id: ''
created_at: '2025-08-10 10:12:35.749955'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/client/.codx/tasks/chats/chats/admin.22bd6213-f08d-4d95-99f5-921d367cd484.yaml
id: 22bd6213-f08d-4d95-99f5-921d367cd484
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: channel
name: admin
parent_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
updated_at: '2025-08-10T11:00:59.582184'
url: ''
users: []
visibility: ''
