board: chats
branch: ''
chat_index: 0
chat_links: []
check_lists: []
child_index: 0
column: chats
column_id: ''
created_at: '2025-11-15 07:34:25.550992'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/client/.codx/tasks/chats/chats/new-task.486d43d7-0f24-43f2-b348-f1604194e5a8.yaml
id: 486d43d7-0f24-43f2-b348-f1604194e5a8
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: task
name: New Task
parent_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
target_project_id: null
updated_at: '2025-11-16T09:46:02.505758'
url: ''
users: []
visibility: ''
