board: kanban
branch: ''
chat_index: 0
chat_links: []
check_lists: []
child_index: 0
column: tasks
column_id: ''
created_at: '2025-11-25 15:11:08.584096'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/.codx/tasks/kanban/tasks/.36e67970-d8f4-4621-ac66-b46a0dd4ef3c.yaml
id: 36e67970-d8f4-4621-ac66-b46a0dd4ef3c
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: chat
name: ''
parent_id: null
parent_project_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
target_project_id: null
updated_at: '2025-11-25T17:24:26.949874'
url: ''
users: []
visibility: ''
