board: Chat manager
branch: ''
chat_index: 0
chat_links: []
check_lists: []
column: To do
column_id: ''
created_at: '2025-08-26 08:25:54.555443'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/.codx/tasks/Chat manager/To do/conversation-test.a52a8374-5f3a-4f2c-abde-77d94cdd3ac3.yaml
id: a52a8374-5f3a-4f2c-abde-77d94cdd3ac3
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages:
- content: We'll discuss about the value of "discussion" chat mode
  created_at: '2025-08-26 08:25:54.553298'
  disable_knowledge: false
  doc_id: 37e3320f-05b9-4a21-b126-3ab871649156
  done: true
  files: []
  hide: false
  images: []
  improvement: false
  is_answer: false
  is_thinking: false
  knowledge_topics: []
  meta_data: {}
  profiles: []
  read_by: []
  role: user
  task_item: ''
  think: ''
  updated_at: '2025-08-26 08:25:54.553327'
  user: null
mode: topic
name: Conversation test
parent_id: 5dd715e3-110b-4c40-b325-08fd0bfb32f1
pinned: false
pr_view: {}
profiles: []
project_id: d4e4b4a9-2281-4970-bff1-f845b4d98456
remote_url: ''
status: ''
tags: []
updated_at: '2025-08-26T08:36:30.289604'
url: ''
users: []
visibility: ''
