board: Default
branch: ''
chat_index: 0
chat_links: []
check_lists: []
column: tasks
column_id: ''
created_at: '2024-12-15T09:38:48.963174'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/api/.codx/tasks/Default/tasks/kanban-models.70d07018-1b2c-4aad-ac7e-686b5cb35e1d.yaml
id: 70d07018-1b2c-4aad-ac7e-686b5cb35e1d
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: task
name: Kanban models
parent_id: '0'
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
updated_at: '2025-01-10T04:34:40.395639'
url: ''
users: []
visibility: ''
