board: Profiles
branch: ''
chat_index: 0
chat_links: []
check_lists: []
column: Profile
column_id: ''
created_at: '2025-11-01 14:31:08.298504'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/client/.codx/tasks/Profiles/Profile/profile-test-profile.15b67291-d0cf-4b57-8d26-4937038836e5.yaml
id: 15b67291-d0cf-4b57-8d26-4937038836e5
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: task
name: Profile test_profile
parent_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
updated_at: '2025-11-01T15:04:21.178321'
url: ''
users: []
visibility: ''
