board: kanban
branch: ''
chat_index: 0
chat_links: []
check_lists: []
child_index: 0
column: tasks
column_id: ''
created_at: '2025-11-15 07:34:25.550992'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/client/.codx/tasks/kanban/tasks/.0773e566-77ff-4106-a36c-7bdc768cb31f.yaml
id: 0773e566-77ff-4106-a36c-7bdc768cb31f
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: chat
name: ''
parent_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
target_project_id: null
updated_at: '2025-11-16T10:13:10.916480'
url: ''
users: []
visibility: ''
