board: kanban
branch: ''
chat_index: 0
chat_links: []
check_lists: []
child_index: 0
column: tasks
column_id: ''
created_at: '2025-11-15 07:34:25.550992'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/client/.codx/tasks/kanban/tasks/.7ac332d0-9d4e-456b-8636-7024e1a05a69.yaml
id: 7ac332d0-9d4e-456b-8636-7024e1a05a69
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: chat
name: ''
parent_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
target_project_id: null
updated_at: '2025-11-16T09:46:13.494089'
url: ''
users: []
visibility: ''
