board: Knowledge search
branch: ''
chat_index: 0
chat_links: []
check_lists: []
column: To Do
column_id: ''
created_at: '2025-07-16 10:35:43.274511'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/.codx/tasks/Knowledge search/To Do/create-a-knowledge-search-dialog.6a283e19-d9c0-41d6-a52d-f00ad48395e7.yaml
id: 6a283e19-d9c0-41d6-a52d-f00ad48395e7
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: chat
name: Create a knowledge search dialog
parent_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
updated_at: '2025-07-16T13:48:10.078343'
url: ''
users: []
visibility: ''
