board: Change manager
branch: ''
chat_index: 0
chat_links: []
check_lists: []
column: chat engine
column_id: ''
created_at: '2025-08-27 06:14:54.276817'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/api/.codx/tasks/Change manager/chat engine/chat-test.1cda0ca5-21cd-43e6-9f12-faba748f6582.yaml
id: 1cda0ca5-21cd-43e6-9f12-faba748f6582
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages:
- content: HI there!
  created_at: '2025-08-27 06:14:54.274710'
  disable_knowledge: true
  doc_id: efbf3bed-f361-4813-a492-58968b59df84
  done: true
  files: []
  hide: false
  images: []
  improvement: false
  is_answer: false
  is_thinking: false
  knowledge_topics: []
  meta_data: {}
  profiles: []
  read_by: []
  role: user
  task_item: ''
  think: ''
  updated_at: '2025-08-27 06:14:54.274739'
  user: admin
- content: Hello! How can I assist you today?
  created_at: '2025-08-27 06:14:54.274710'
  disable_knowledge: false
  doc_id: df052663-5fe5-45ef-bb91-b70cd16a6d31
  done: true
  files: []
  hide: false
  images: []
  improvement: false
  is_answer: false
  is_thinking: false
  knowledge_topics: []
  meta_data: {}
  profiles: []
  read_by: []
  role: assistant
  task_item: ''
  think: ''
  updated_at: '2025-08-27 06:14:54.274739'
  user: null
mode: chat
name: Chat test
parent_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
updated_at: '2025-08-27T06:20:05.075699'
url: ''
users:
- admin
visibility: ''
