board: codx-junior
branch: ''
chat_index: 0
chat_links: []
check_lists: []
column: '2025-05-25'
column_id: ''
created_at: '2025-07-13 08:11:04.484199'
description: ''
doc_id: null
file_list: []
file_path: /shared/codx-junior/api/.codx/tasks/codx-junior/2025-05-25/new-task.5c67dc06-e43d-4c49-9dfb-04f43686e9b3.yaml
id: 5c67dc06-e43d-4c49-9dfb-04f43686e9b3
kanban_id: ''
knowledge_topics: []
llm_model: ''
message_id: null
messages: []
mode: chat
name: New Task
parent_id: null
pinned: false
pr_view: {}
profiles: []
project_id: null
remote_url: ''
status: ''
tags: []
updated_at: '2025-07-13T08:11:28.491303'
url: ''
users: []
visibility: ''
